apiVersion: v1
kind: Service
metadata:
  name: wine-flask-service
  namespace: aleksandarm
spec:
  selector:
    app: wine-flask-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
