apiVersion: v1
kind: PersistentVolume
metadata:
  name: wine-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/aleksandarm/wine-data  # Putanja na nodu gde je postavljen CSV fajl
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wine-pvc
  namespace: aleksandarm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
